ministryofjustice/hmpps-prisoner-profile

- cypress.config.ts
- docker-compose.yml
- feature.env
- integration_tests/e2e/login.cy.ts
- integration_tests/mockApis/dpsHomepage.ts
- integration_tests/pages/dpsHomePage.ts
- integration_tests/pages/index.ts
- integration_tests/support/commands.ts
- server/config.ts
- server/errorHandler.test.ts
- server/routes/index.test.ts
- server/routes/index.ts
- server/views/pages/index.njk
Initial commit to enable development to start.
> Initial repo setup

- assets/sass/application.sass
- assets/sass/components/_status.scss
- server/data/overviewPage.ts
- server/routes/index.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/index.njk
- server/views/partials/overviewPage/macros/statusListMacro.njk
- server/views/partials/overviewPage/macros/statusesMacro.njk
- server/views/partials/overviewPage/mainBody.njk
- server/views/partials/overviewPage/status/statusList.njk
Create statuses macro (#38)
Add formatDate filter
> ALIGN-38: Statuses component

- assets/sass/application.sass
- assets/sass/components/_miniSummary.scss
- assets/sass/helpers.scss
- cypress.config.ts
- integration_tests/e2e/overviewPage.cy.ts
- integration_tests/mockApis/dpsOverviewPage.ts
- integration_tests/pages/overviewPage.ts
- package-lock.json
- server/data/miniSummary/miniSummary.ts
- server/routes/index.test.ts
- server/routes/index.ts
- server/services/overviewPage.test.ts
- server/views/pages/overviewPage.njk
- server/views/partials/overviewPage/mainBody.njk
- server/views/partials/overviewPage/miniSummaryBoxes/macro.njk
- server/views/partials/overviewPage/miniSummaryBoxes/miniSummaryBoxList.njk
This PR includes the mini summary macro for box style 1 and 2 (ALIGN-43)
> ALIGN-39 - Mini summary macro - box style 1 and 2

- assets/sass/components/_miniSummary.scss
- assets/sass/components/_summary-card.scss
- integration_tests/pages/overviewPage.ts
- server/views/partials/overviewPage/macros/summaryCardMacro.njk
- server/views/partials/overviewPage/miniSummaryBoxes/macro.njk
A follow up to both #21 and #20 combining the two ways of doing the card components into one
> ALIGN-41 - Align card header/bodies with summary macro

- package-lock.json
- package.json
Update typescript to 4.9.5 (#53)
> ALIGN-53: Update dependencies

- server/data/hmppsAuthClient.ts
> Align 45 amend api call

- integration_tests/e2e/overviewPage.cy.ts
- integration_tests/pages/overviewPage.ts
- server/data/profileBanner/profileBanner.ts
- server/mappers/headerMappers.ts
- server/routes/index.ts
- server/views/pages/index.njk
- server/views/pages/overviewPage.njk
- server/views/pages/personalDetailsPage.njk
- server/views/pages/photoPage.njk
- server/views/partials/layout.njk
- server/views/partials/profileBanner/macros/tabLinksMacro.njk
- server/views/partials/profileBanner/profileBannerBottom.njk
- Add personal details page to route
- Support the active/inactive tabs for which is selected
- Reduce the amount of data required to pass into each page render
> CDPS-46 - Add personal details page and simplify templates

- integration_tests/e2e/personalPage.cy.ts
- integration_tests/index.d.ts
- integration_tests/mockApis/prison.ts
- integration_tests/pages/personalPage.ts
- integration_tests/support/commands.ts
- server/data/interfaces/prisonApiClient.ts
- server/data/localMockData/prisoner.ts
- server/data/prisonApiClient.ts
- server/interfaces/pages/personalPage.ts
- server/interfaces/prisonApi/profileInformation.ts
- server/interfaces/prisoner.ts
- server/routes/common/api.ts
- server/routes/index.ts
- server/services/offenderService.ts
- server/services/overviewPageService.test.ts
- server/services/personalPageService.test.ts
- server/services/personalPageService.ts
- server/services/workAndSkillsPageService.test.ts
- server/views/macros/summaryListRow.njk
- server/views/partials/personalPage/appearance.njk
- tests/mocks/prisonApiClientMock.ts
This PR also introduces a couple new helpers for testing:
- E2E tests
- Get/Find by data qa
- Unit tests
- a mocks folder for API mocks so we only have to update one place when the interface is updated and can setup what's needed in tests
> CDPS-44 - Personal page appearance card

- assets/scss/components/_sidebar.scss
- integration_tests/pages/personalPage.ts
- server/views/pages/personalPage.njk
- server/views/partials/personalPage/nextOfKin.njk
- Update the title of the next of kin summary card
- Decrease the margin on the sidebar
> CDPS-109 - personal page visual changes

- architecture-decision-record/0004-use-user-token-for-case-notes-api.md
- architecture-decision-record/README.md
- assets/scss/pages/_case-notes-page.scss
- assets/scss/typography.scss
- integration_tests/e2e/caseNotesPage.cy.ts
- integration_tests/e2e/login.cy.ts
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/prison.ts
- integration_tests/pages/notFoundPage.ts
- server/app.ts
- server/controllers/alertsController.test.ts
- server/controllers/alertsController.ts
- server/controllers/caseNotesController.test.ts
- server/controllers/caseNotesController.ts
- server/controllers/overviewController.ts
- server/data/enums/caseNoteSource.ts
- server/data/enums/role.ts
- server/data/localMockData/caseLoad.ts
- server/data/profileBanner/profileBanner.ts
- server/mappers/headerMappers.ts
- server/middleware/setUpCurrentUser.ts
- server/middleware/setUpPageNotFound.ts
- server/routes/index.ts
- server/services/caseNotesService.test.ts
- server/services/caseNotesService.ts
- server/utils/roleHelpers.ts
- server/views/notFound.njk
- server/views/partials/caseNotesPage/macros/caseNoteCard.njk
- server/views/partials/overviewPage/macros/actionsBlockMacro.njk
- server/views/partials/overviewPage/sideBar.njk
CDPS-150, CDPS-152, CDPS-153, CDPS-163
> CDPS-147: Case Notes Mop Up

- server/mappers/headerMappers.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/partials/profileBanner/profileBannerTop.njk
I will create a follow up PR with unit tests and end to end tests
> CDPS-173 - alternative-banners

- .env-local-wiremock
- cypress.config.ts
- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/mockApis/adjudications.ts
- integration_tests/mockApis/prison.ts
- server/config.ts
- server/data/adjudicationsApiClient.test.ts
- server/data/adjudicationsApiClient.ts
- server/data/index.ts
- server/data/interfaces/adjudicationsApiClient.ts
- server/data/interfaces/prisonApiClient.ts
- server/data/prisonApiClient.test.ts
- server/data/prisonApiClient.ts
- server/services/activePunishmentsService.test.ts
- server/services/activePunishmentsService.ts
- server/services/index.ts
- server/services/overviewPageService.test.ts
- server/services/overviewPageService.ts
- server/services/workAndSkillsPageService.test.ts
- tests/mocks/adjudicationsApiClientMock.ts
- tests/mocks/prisonApiClientMock.ts
https://dsdmoj.atlassian.net/browse/NN-5365
> NN-5365: get adjudication data from AdjudicationsAPI instead of PrisonAPI

- .env-local-wiremock
- cypress.config.ts
- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/mockApis/adjudications.ts
- integration_tests/mockApis/prison.ts
- server/config.ts
- server/data/adjudicationsApiClient.test.ts
- server/data/adjudicationsApiClient.ts
- server/data/index.ts
- server/data/interfaces/adjudicationsApiClient.ts
- server/data/interfaces/prisonApiClient.ts
- server/data/prisonApiClient.test.ts
- server/data/prisonApiClient.ts
- server/services/activePunishmentsService.test.ts
- server/services/activePunishmentsService.ts
- server/services/index.ts
- server/services/overviewPageService.test.ts
- server/services/overviewPageService.ts
- server/services/workAndSkillsPageService.test.ts
- tests/mocks/adjudicationsApiClientMock.ts
- tests/mocks/prisonApiClientMock.ts
https://dsdmoj.atlassian.net/browse/NN-5365
> Revert "Revert "NN-5365: get adjudication data from AdjudicationsAPI instead of PrisonAPI (#240)" (#243)"

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- server/controllers/overviewController.ts
Remove appointments enabled as condition for displaying activities link
> Remove activities enabled prisons for preprod and prod

- server/routes/index.ts
Reverts ministryofjustice/hmpps-prisoner-profile#307
> Revert "Remove middleware from overview to diagnose memory leak"

- integration_tests/e2e/addAlertPage.cy.ts
- integration_tests/e2e/addCaseNotePage.cy.ts
- integration_tests/e2e/alertsPage.cy.ts
- integration_tests/e2e/personalPage.cy.ts
- integration_tests/e2e/photoPage.cy.ts
- integration_tests/index.d.ts
- integration_tests/mockApis/prison.ts
- integration_tests/support/commands.ts
- server/controllers/prisonerScheduleController.test.ts
- server/data/adjudicationsApiClient.ts
- server/data/caseNotesApiClient.ts
- server/data/curiousApiClient.ts
- server/data/prisonApiClient.ts
Reverts ministryofjustice/hmpps-prisoner-profile#309
> Revert "Remove mock data catch from the prison API"

- server/mappers/headerMappers.ts
This reverts commit db5088a773da37f8d5555f5e2c604a197c054dff.
> Revert "point csra link to old history page (#314)"

- server/middleware/setUpAuthentication.ts
This mirrors the change added in the new homepage [here](https://github.com/ministryofjustice/hmpps-digital-prison-services/pull/84)
> Implement auth handler from DPS Core

- helm_deploy/values-prod.yaml
the rules are not firing in prod as expected.
we'll run this for a couple of weeks.
> CDPS-586 switch to detection only mode.

- server/services/overviewPageService.test.ts
- server/services/overviewPageService.ts
Updated based on the logic listed here: 
https://dsdmoj.atlassian.net/browse/NN-2579
> CDPS-592: Don't display recognised listener unless yes when given no suitible

- helm_deploy/values-dev.yaml
Additional Audit log switched on, and defaults applied from previous incarnation of generic helm template
> MODSEC - DEV -  add all relevant rules and Audit log on fully

- helm_deploy/values-dev.yaml
- Keep it simple based on CP advice first
> MODSEC- DEV-  detection only / audit on 

- server/services/caseNotesService.ts
- server/utils/utils.ts
Fix alerts sorting bug
Tidy code
> CDPS-593: Fix case notes sorting bug

- helm_deploy/values-dev.yaml
Enable new PLP/VC2 goals pages in dev environment
https://dsdmoj.atlassian.net/browse/RR-584
> RR-584 - Enable new PLP/VC2 goals pages in dev environment

- server/interfaces/mappers/personalLearningPlanActionPlanMapper.ts
PR to fix the ordering of PLP goals on the Work & Skills tab
> RR-584 - Fixes the ordering of PLP goals

- server/views/partials/new_workAndSkillsPage/goals/problemRetrievingGoals.njk
fix capitalisation of the word goals on the error messaging
> RR-584 fix capitalisation of the word goals on the error messaging

- helm_deploy/values-preprod.yaml
- server/routes/index.ts
This PR enables the feature toggle for the new Work & Skills tab in preprod.
It also fixes a small problem in environments where the feature toggle has not been enabled (this is what you found earlier @chrimesdev )
> RR-584 - Enable feature toggle in preprod

- server/routes/index.ts
Fix the url path for the VC2 goals page
> RR-584 fix the url path for the VC2 goals page

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
looks like theres some interference from other rules. 
We will test this in dev then ask for it to be rolled out urgently.
> CDPS-571 update rules to simple detection and audit only.

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Semi colon should have been a comma 👎🏻
> Cdps 579 fix colon

- server/views/partials/workAndSkillsPage/goals/noGoals.njk
Update the empty state content if a prisoner has no goals in either the PLP or VC2 service
https://dsdmoj.atlassian.net/browse/RR-651
> RR-651 update the empty state content for no goals in either service

- assets/scss/components/_api-error.scss
- integration_tests/e2e/overviewPage.cy.ts
- integration_tests/e2e/professionalContactsPage.cy.ts
- integration_tests/pages/overviewPage.ts
- integration_tests/pages/page.ts
- integration_tests/pages/professionalContactsPage.ts
- server/controllers/professionalContactsController.test.ts
- server/controllers/professionalContactsController.ts
- server/services/overviewPageService.ts
- server/services/professionalContactsService.test.ts
- server/services/professionalContactsService.ts
- server/utils/nunjucksSetup.ts
- server/utils/result/result.test.ts
- server/utils/result/result.ts
- server/utils/utils.ts
- server/views/pages/professionalContacts/professionalContactsPage.njk
> CDPS-670: Making the professional contacts page resilient against keyworker API failures

- helm_deploy/hmpps-prisoner-profile/values.yaml
- readme/building_and_running.md
- server/config.ts
This PR adds a new feature toggle for the new Curious Courses & Qualifications History display on the W&S tab
> RR-650 - Add feature toggle for the new Curious Courses & Qualifications History 

- server/controllers/appointmentController.ts
- server/controllers/appointmentsController.test.ts
Court name needed in Notify template for BVL. 
Will update template once data is being passed through
> MAP-849 added court name to data sent to Notify

- integration_tests/e2e/alerts/alertsPage.cy.ts
- integration_tests/e2e/profileBanner.cy.ts
- integration_tests/mockApis/alertsApi.ts
- integration_tests/support/commands.ts
- server/@types/express/index.d.ts
- server/controllers/alertsController.test.ts
- server/controllers/alertsController.ts
- server/controllers/caseNotesController.test.ts
- server/controllers/caseNotesController.ts
- server/controllers/overviewController.test.ts
- server/controllers/overviewController.ts
- server/data/alertsApiClient.ts
- server/data/interfaces/alertsApi/Alert.ts
- server/data/interfaces/alertsApi/alertsApiClient.ts
- server/data/localMockData/pagedAlertsMock.ts
- server/middleware/getPrisonerDataMiddleware.ts
- server/routes/index.ts
- server/services/alertsService.test.ts
- server/services/alertsService.ts
- server/services/mappers/alertMapper.ts
CDPS-779: Use Alerts API to get counts for tabs in enabled prisons
Add defined properties to `Request.middleware` interface declaration
> CDPS-773: Add secondary sort parameters to alerts list queries for Alerts API

- helm_deploy/hmpps-prisoner-profile/values.yaml
- helm_deploy/values-dev.yaml
This PR enables the feature toggle for the new "In Prison Courses & Qualifications" card on the Work & Skills tab, in all environments.
> RR-650 - Enable feature toggle in prod

- helm_deploy/hmpps-prisoner-profile/Chart.yaml
Reverts ministryofjustice/hmpps-prisoner-profile#635
> Revert "CDPS-740: Update helm dependencies"

- helm_deploy/hmpps-prisoner-profile/values.yaml
- server/config.ts
Please do NOT deploy to prod until 9:00am on Tuesday 6 Aug 2024
> MAP-1441 enable functional mailbox for wormwood scrubs

- server/controllers/appointmentController.ts
- server/controllers/appointmentsController.test.ts
- server/validators/prePostAppointmentValidator.test.ts
- server/validators/prePostAppointmentValidator.ts
- server/views/pages/appointments/prePostAppointments.njk
> BAVL-335: Add CVP not known radio pattern

- server/controllers/caseNotesController.test.ts
- server/controllers/caseNotesController.ts
- server/controllers/prisonerLocationHistoryController.test.ts
- server/data/caseNotesApiClient.test.ts
- server/data/caseNotesApiClient.ts
- server/data/interfaces/caseNotesApi/UpdateCaseNoteForm.ts
- server/data/interfaces/caseNotesApi/caseNotesApiClient.ts
- server/services/caseNotesService.test.ts
- server/services/caseNotesService.ts
- server/services/prisonerLocationHistoryService.test.ts
pass Caseload ID into create case notes request body, and
remove unused interface
> Refactor case notes api client

- assets/scss/local.scss
- integration_tests/e2e/alerts/alertsPage.cy.ts
- integration_tests/e2e/caseNotesPage.cy.ts
- integration_tests/mockApis/alertsApi.ts
- integration_tests/pages/alertsPage.ts
- integration_tests/pages/caseNotesPage.ts
- server/controllers/alertsController.test.ts
- server/controllers/alertsController.ts
- server/controllers/caseNotesController.test.ts
- server/controllers/caseNotesController.ts
- server/controllers/overviewController.ts
- server/controllers/personal/personalController.ts
- server/data/alertsApiClient.ts
- server/data/caseNotesApiClient.ts
- server/data/interfaces/alertsApi/Alert.ts
- server/mappers/headerMapper.test.ts
- server/mappers/headerMappers.ts
- server/middleware/getPrisonerDataMiddleware.test.ts
- server/middleware/getPrisonerDataMiddleware.ts
- server/routes/index.ts
- server/services/alertsService.test.ts
- server/services/mappers/alertMapper.ts
- server/views/pages/alerts/alertsPage.njk
- server/views/pages/caseNotes/caseNotesPage.njk
- server/views/partials/profileBanner/macros/alertsMacro.njk
- server/views/partials/profileBanner/profileBannerBottom.njk
Display banners when unavailable
> CDPS-940: Make Alerts and Case Notes API calls resilient to failure.

- helm_deploy/values-prod.yaml
GO LIVE FOR BVLS. DO NOT MERGE UNTIL READY (@brightonsbox)
> BAVL-425 PR to enable the feature toggle to use the new BVLS service in production for creation of Video Link Court Hearings.

- server/controllers/appointmentController.ts
- server/controllers/appointmentsController.test.ts
- server/data/interfaces/whereaboutsApi/Appointment.ts
- server/views/pages/appointments/prePostAppointmentConfirmation.njk
> BAVL-421: Fix content on confirmation page when amending a video booking

- package-lock.json
- package.json
- server/controllers/appointmentController.ts
- server/middleware/setUpHealthChecks.ts
> Update npm to v11

- integration_tests/e2e/personal/edit/editDietAndFoodAllergies.cy.ts
- integration_tests/e2e/personal/edit/editMedicalDiet.cy.ts
- integration_tests/index.d.ts
- integration_tests/mockApis/healthAndMedication.ts
- integration_tests/support/commands.ts
- server/controllers/personal/personalController.test.ts
- server/controllers/personal/personalController.ts
- server/data/healthAndMedicationApiRestClient.test.ts
- server/data/healthAndMedicationApiRestClient.ts
- server/data/interfaces/healthAndMedicationApi/healthAndMedicationApiClient.ts
- server/data/interfaces/prisonPersonApi/prisonPersonApiClient.ts
- server/data/localMockData/healthAndMedicationApi/healthAndMedicationMock.ts
- server/data/localMockData/healthAndMedicationApi/referenceDataMocks.ts
- server/data/localMockData/healthMock.ts
- server/services/interfaces/personalPageService/PersonalPage.ts
- server/services/personalPageService.test.ts
- server/services/personalPageService.ts
- server/validators/personal/dietAndFoodAllergiesValidator.ts
- server/views/pages/edit/dietAndFoodAllergies.njk
- tests/mocks/personalPageServiceMock.ts
- tests/mocks/prisonPersonApiClientMock.ts
This brings the UI in line with the changes made to the API [here](https://github.com/ministryofjustice/hmpps-health-and-medication-api/pull/9)
> CDPS-1152: Edit 'other' fields and personalised diet

- assets/js/militaryRankRadios.js
- integration_tests/e2e/personal/militaryHistory/conflicts.cy.ts
- integration_tests/e2e/personal/militaryHistory/militaryServiceInformation.cy.ts
- integration_tests/pages/conflictsPage.ts
- integration_tests/pages/militaryServiceInformationPage.ts
- server/controllers/militaryRecordsController.test.ts
- server/controllers/militaryRecordsController.ts
- server/data/interfaces/personIntegrationApi/personIntegrationApiClient.ts
- server/data/localMockData/personIntegrationReferenceDataMock.ts
- server/routes/militaryRecordsRouter.ts
- server/routes/personalRouter.ts
- server/services/auditService.ts
- server/services/militaryRecordsService.ts
- server/validators/personal/militaryServiceInformationValidator.test.ts
- server/validators/personal/militaryServiceInformationValidator.ts
- server/views/pages/militaryRecords/conflicts.njk
- server/views/pages/militaryRecords/militaryServiceInformation.njk
- server/views/partials/personalPage/personalDetails.njk
CDPS-1193: Military service information wash up
> CDPS-1138: Conflicts page

- server/services/utils/permissions/access/getCaseNotesAccessStatusCode.test.ts
- server/services/utils/permissions/access/getCaseNotesAccessStatusCode.ts
This reverts commit 2f76e269432003791be3b4c929b08004a490ea52.
> Revert "CDPS-1298: Limit access to case notes (#894)"

- readme/testing.md
- server/controllers/alertsController.test.ts
- server/controllers/alertsController.ts
- server/controllers/caseNotesController.test.ts
- server/controllers/caseNotesController.ts
- server/controllers/overviewController.test.ts
- server/controllers/overviewController.ts
- server/controllers/personal/personalController.ts
- server/mappers/headerMappers.ts
- server/routes/imageRouter.ts
- server/routes/index.ts
- server/services/permissionsService.test.ts
- server/services/permissionsService.ts
- server/services/utils/permissions/access/getCaseNotesAccessStatusCode.test.ts
- server/services/utils/permissions/access/getCaseNotesAccessStatusCode.ts
- server/services/utils/permissions/getCaseNotesPermissions.test.ts
- server/services/utils/permissions/getCaseNotesPermissions.ts
- server/utils/roleHelpers.ts
- tests/mocks/userMocks.ts
This reverts commit 50b656e26c13a270127e161cc0a8439a891b0c27.
> Revert "CDPS-1289: Fix case note permissions (#909)"

- server/views/partials/overviewPage/personalDetails/personalDetails.njk
Moving a column from the right hand side to the left hand side of the personal details section on the overview page.
> CDPS-1391 Preferred name washup

- assets/js/profilePhotoCropper.js
- assets/scss/components/_image-cropper.scss
- server/views/pages/edit/photo/editPhoto.njk
- selection is now centred by default
- selection is now the govuk focus colour
- the user flow is changed to be more clear
- fixed issue with photo scale when rotating and not moving
- Removed duplicate code as a result of this
> CDPS-1430 & CDPS-1429: Update pages based on feedback

- .gitleaks/.gitleaksignore
- .gitleaks/config.toml
- .husky/pre-commit
- package-lock.json
- package.json
This reverts commit 26080bfd5348a1895484f068999f825b5bcaef31.
> Revert "CDPS-1458: Setting up hmpps-precommit-hooks (#1036)"
