ministryofjustice/hmpps-prisoner-profile

docker-compose.yml
There is a dash missing from the docker-compose.yml
=> Fixed typo - added missing dash

integration_tests/e2e/caseNotesPage.cy.ts, integration_tests/e2e/personalPage.cy.ts, integration_tests/index.d.ts, integration_tests/mockApis/auth.ts, integration_tests/mockApis/prison.ts, integration_tests/support/commands.ts, server/mappers/headerMappers.ts, server/middleware/populateCurrentUser.ts, server/middleware/setUpCurrentUser.ts, server/utils/nunjucksSetup.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/macros/conditionallyShow.njk, server/views/pages/personalPage.njk
This PR creates the scaffolding in production and test code for us to be able to add conditional viewing. 
The frontend macro for this allows for:
- Showing/Hiding content based on a condition passed in
- E.g. Checking for roles, case loads, etc
- Showing placeholder content if the condition isnt met
- Putting data in for E2E tests to read whether or not something has been conditionally shown (e.g. `data-qa='hidden-X'`)
Additionally this sets up the middleware for letting us check users roles and caseloads
=> Setup for conditional based viewing

helm_deploy/values-prod.yaml
4 is the standard number of pods we use in production.
=> Increasing number of pods in production to 4

integration_tests/mockApis/prison.ts, server/data/localMockData/nonAssociations.ts, server/data/prisonApiClient.test.ts, server/data/prisonApiClient.ts, server/interfaces/nonAssociationDetails.ts, server/services/overviewPageService.test.ts, server/services/overviewPageService.ts
As NA API endpoint now can filter by current prison and also active only - making use of this to simplify the code
=> NON-160 filter inactive and NA in a different prison

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, readme/building_and_running.md, server/config.ts, server/interfaces/overviewPage.ts, server/services/overviewPageService.test.ts, server/services/overviewPageService.ts, server/utils/utils.ts, server/views/partials/overviewPage/alerts/alerts.njk
Adding "Non-associations" link:
- Component already exists but is missing the link to a prisoners non associations.
- Feature flag added that displays/doesn't display the link depending on the active caseload.
=> NON-248: Non-Associations Link

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
The 'Alerts' section will show the link to the prisoner non-associations in the following prisons: FNI,ISI,LGI,RSI
**NOTE**: This can't be merged/deployed until we start the private beta in these prisons. We'll keep this PR in draft until then.
=> NON-261: Show link for non-associations private beta prisons

integration_tests/e2e/addAlertPage.cy.ts, integration_tests/e2e/addCaseNotePage.cy.ts, integration_tests/e2e/alertsPage.cy.ts, integration_tests/e2e/personalPage.cy.ts, integration_tests/e2e/photoPage.cy.ts, integration_tests/index.d.ts, integration_tests/mockApis/prison.ts, integration_tests/support/commands.ts, server/controllers/prisonerScheduleController.test.ts, server/data/adjudicationsApiClient.ts, server/data/curiousApiClient.ts, server/data/incentivesApiClient.ts, server/data/interfaces/prisonApiClient.ts, server/data/nonAssociationsApiClient.ts, server/data/prisonApiClient.ts, server/data/restClient.ts, server/services/overviewPageService.test.ts, server/services/overviewPageService.ts, server/services/personalPageService.test.ts
Following on from #327 , this is another difference we have between other apps that could be causing memory issues.
Additionally, this has been hiding issues for a while where we're accidentally swallowing 500 errors, removing this should help alleviate that. However as some endpoints _do_ return 404s, we need to catch those ones and ignore them if it's approproate
=> CDPS-387: Remove local mock data

helm_deploy/values-prod.yaml
Based on https://sysdig.com/blog/kubernetes-limits-requests/ we're currently running a bare minimum request size for the containers for the profile. This is causing a few issues for the Horizontal Pod Autoscale settings. `targetCPUUtilizationPercentage` is based on the minimum CPU request size so the scaling needs to take into account the limit.  
By making the calculation `targetRequest% = targetValue% (range 0-100) * (limit/request)%` should give what's needed - this can be more than 100%.
we've done 2 things:
- upped the `limitRange` settings for minimum `defaultRequest` size to `100m` CPU (0.1 vCPU) - in  PR:https://github.com/ministryofjustice/cloud-platform-environments/pull/17635 
- set the `targetCPUUtilizationPercentage` HPA to 1600% (which is 80% of the total CPU limit).
We'll …
=> CDPS-401 - update to 1600% for requests (80% of limit)

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, integration_tests/e2e/overviewPage.cy.ts, integration_tests/pages/overviewPage.ts, server/config.ts, server/interfaces/overviewPage.ts, server/services/overviewPageService.test.ts, server/services/overviewPageService.ts, server/utils/utils.ts, server/views/partials/overviewPage/alerts/alerts.njk
The link to prisoner's non-associations (in the Non-associations service) will be shown always.
Previously we had a short list of prisons that could see these links but we want to show these links all the time now as there is no harm in doing so.
=> NON-305: Always show links to non-associations in overview page

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Modsec is firing 406 errors for a number of rules. We need to let the service to run in these scenarios, potentially due to false positives. 
we'll investigate why this is triggering in a later ticket.
=> CDPS-571 -  🔒 add modsec rules. 

server/middleware/setUpWebSession.ts
Explicitly name cookie in Prisoner Profile rather than relying on express-session default connect.sid.
=> Renamed cookie to match project name.

helm_deploy/values-dev.yaml
We've added tagging to dev to allow us to search for `github_team=connect-dps` and `namespace=hmpps-prisoner-profile-dev` 
- this should help narrow down the logs in `DetectionOnly` mode in modsecurity
Clean branch used.
=> Add Sec Default rule with appropriate tagging. V1.1

helm_deploy/values-dev.yaml
- adding some example modsecurity settings - part back in from generic service chart - was commented out here:
https://github.com/ministryofjustice/hmpps-helm-charts/commit/4ce3afdf951a6e6b433a67cd39336a4a91901704
- switch on audit.
=> V2 - using commented out default from generic service.

helm_deploy/values-preprod.yaml
previous modsec fixes somehow removed the env devlaration from preproduction helm values. fix is here.
=> CDPS-621 somehow missed an missing `env:` declaration in the preprod values

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, server/config.ts, server/data/educationAndWorkPlanApiClient.test.ts, server/data/educationAndWorkPlanApiClient.ts, server/data/interfaces/educationAndWorkPlanApiClient.ts, server/data/localMockData/actionPlanResponse.ts, server/interfaces/educationAndWorkPlanApi/actionPlanResponse.ts, server/interfaces/educationAndWorkPlanApi/goalResponse.ts, server/interfaces/educationAndWorkPlanApi/stepResponse.ts
This PR adds the new REST API client for the Education And Work Plan API (PLP API)
Functionally it is equivalent to what we've done in PLP UI and CIAG UI, but the patterns are slightly different. I've adopted and followed the patterns already established in this code base, rather than trying to do something new. Specifically:
* I have not imported the swagger spec to generate the types. Instead I have manually implemented them in `server/interfaces/educationAndWorkPlanApi` which is consistent with how/where all the other API response types are defined.
* I have defined and implemented an interface for the REST API client class. We've not bothered with that in PLP & CIAG, but all the other client classes in this code base have one, so I've followed suit.
* What we would know and love as a …
=> RR-575 - Add new REST API client for the Education And Work Plan API (PLP API)

integration_tests/e2e/workAndSkillsPage.cy.ts, integration_tests/pages/workAndSkillsPage.ts, server/views/partials/new_workAndSkillsPage/employabilitySkills.njk
Add information text to the Employability skills section on the new Work & Skills tab as part of the work that the PLP team are doing in the EPIC https://dsdmoj.atlassian.net/browse/RR-575
https://dsdmoj.atlassian.net/browse/RR-583
Prisoner with employability skills (`G6123VU`)
Prisoner without employability skills (`G9981UK`)
=> RR-583 add info text to the employability skills section

server/data/localMockData/actionPlanResponse.ts, server/data/localMockData/personalLearningPlanActionPlan.ts, server/interfaces/mappers/personalLearningPlanActionPlanMapper.test.ts, server/interfaces/mappers/personalLearningPlanActionPlanMapper.ts, server/interfaces/personalLearningPlanGoals.ts, server/services/personalLearningPlanService.test.ts, server/services/personalLearningPlanService.ts
This PR is not massive, but adds some important classes relating to getting PLP Goal data. It adds:
* A couple of abstractions of the data that the PLP API returns - `PersonalLearningPlanActionPlan` and `PersonalLearningPlanGoal`. These are basically view models and are not tied to the API response data
* A mapper function, to map between `ActionPlanResponse` (the API response data) and `PersonalLearningPlanActionPlan` (the above view model)
* A service interface `PersonalLearningPlanService` and a concrete implementation `EducationAndWorkPlanApiPersonalLearningPlanService` that uses the `EducationAndWorkPlanApiClient` (aka. PLP API client) to get the PLP Goal related data
The PLP dev team will be familiar with this approach as this is what we've been doing throughout in the PLP and CIAG …
=> RR-575 - Add new PLP service with implementation for Education & Work Plan API

server/views/pages/new_workAndSkills.njk
As part of the work the PLP team are doing, re-order the sections on the new Work & skills page.
> Currently they are in this order:
> - Courses and qualifications
> - Work and activities
> - Employability skills
> - Goals
> - Functional skills levels
> 
> We would like to reorder them as such:
> 
> - Functional skills levels
> - Courses and qualifications
> - Work and activities
> - Goals
> - Employability skills
https://dsdmoj.atlassian.net/browse/RR-585
=> RR-585 reorder the work and skills tab sections

server/data/localMockData/actionPlanResponse.ts, server/data/localMockData/personalLearningPlanActionPlan.ts, server/interfaces/mappers/personalLearningPlanActionPlanMapper.test.ts, server/interfaces/mappers/personalLearningPlanActionPlanMapper.ts, server/interfaces/personalLearningPlanGoals.ts
This PR adds the last updated by/at fields to `PersonalLearningPlanActionPlan` and `PersonalLearningPlanGoal`, as I forgot to add these when I first committed the types and mapper functions.
The only minor bit of complexity here is that the last updated by/at fields for the `PersonalLearningPlanActionPlan` needs to be the values from the most recently updated `PersonalLearningPlanGoal`
=> RR-584 - Map the last updated by/at fields into `PersonalLearningPlanActionPlan`

integration_tests/e2e/vc2GoalsPage.cy.ts, integration_tests/e2e/workAndSkillsPage/workAndSkillsCoursesAndQualifications.cy.ts, integration_tests/e2e/workAndSkillsPage/workAndSkillsEmployabilitySkills.cy.ts, integration_tests/e2e/workAndSkillsPage/workAndSkillsFunctionalSkills.cy.ts, integration_tests/e2e/workAndSkillsPage/workAndSkillsGoals.cy.ts, integration_tests/e2e/workAndSkillsPage/workAndSkillsPage.cy.ts, integration_tests/e2e/workAndSkillsPage/workAndSkillsWorkAndActivities.cy.ts, integration_tests/index.d.ts, integration_tests/mockApis/curiousApi.ts, integration_tests/support/commands.ts
This PR does a little refactoring to the cypress wiremock stubs in respect of the Curious API (to make it easier for a cypress test to say it wants one that returns goals, one that returns no goals, or one that returns an error); and then adds the skeleton methods for new cypress tests that we are about to implement
The new cypress tests are all defined with `it.skip` for the time being - they have the correct scenario description and setup in respect of wiremock stubs; the last thing they need is for the relevant assertions to be written for the rendered page content which will come after @chrimesdev 's current work
=> RR-584 - Skeleton cypress tests for new Goals summary card scenarios on W&S tab

integration_tests/e2e/workAndSkillsPage/workAndSkillsGoals.cy.ts, integration_tests/mockApis/curiousApi.ts, server/services/workAndSkillsPageService.test.ts, server/services/workAndSkillsPageService.ts
This PR fixes a bug which centres around some poor/inconsistent responses from the Curious API for prisoners without any goals.
From testing in `dev` we have found that some prisoners get a 200 response with a response body like this:
```
{
"prn": "G9981UK",
"employmentGoals": [],
"personalGoals": [],
"longTermGoals": [],
"shortTermGoals": []
}
```
whilst others get a 404 response with a response body like this:
```
{
"errorCode": "VC4004",
"errorMessage": "Resource not found",
"httpStatusCode": 404
}
```
This PR handles that inconsistency 🙄 , with suitable unit and cypress tests to prove and aid documentation of this "odd-ness" !
=> RR-584 - Fixes the handling of inconsistent Curious API response for prisoners without goals

server/data/localMockData/personalLearningPlanActionPlan.ts, server/interfaces/mappers/personalLearningPlanActionPlanMapper.test.ts, server/interfaces/mappers/personalLearningPlanActionPlanMapper.ts, server/interfaces/personalLearningPlanGoals.ts, server/views/partials/workAndSkillsPage/goals/plpAndVc2Goals.njk, server/views/partials/workAndSkillsPage/goals/plpGoalsOnly.njk
This PR sets the PLP Goal numbering on the W&S tab based on goal creation date rather than loop index.
=> RR-622 - Add and correctly populate `sequenceNumber` to the `PersonalLearningPlanGoal` view model

server/utils/nunjucksSetup.ts, server/views/partials/workAndSkillsPage/goals/plpAndVc2Goals.njk, server/views/partials/workAndSkillsPage/goals/plpGoalsOnly.njk
This PR changes the W&S tab when rendering PLP Goals, to support multiline text.
It does this in the exact same way that we have already done in PLP, by adding a nunjucks filter called `formatMultilineText` which is basically a pseudonym for the terribly named standard inbuilt [nl2br filter](https://mozilla.github.io/nunjucks/templating.html#nl2br)
It changes this:
to this:
=> RR-643 - Add nunjucks filter to render multiline text; use in rendering of Goals on W&S tab

assets/scss/local.scss, server/utils/nunjucksSetup.ts, server/views/partials/workAndSkillsPage/goals/plpAndVc2Goals.njk, server/views/partials/workAndSkillsPage/goals/plpGoalsOnly.njk
This PR replaces the use of the `formatMultilineText` and `safe` filters with a pure css solution.
The problem with using `formatMultilineText` is that it replaces `\n` with `<br />`. Because the text now contains html that needs to be rendered we needed to use the `safe` filter. And because we are using the `safe` filter on user entered text (eg: Goal title), it means that any html that the user has entered into the field is rendered as markup, rather than being escaped. This is essentially a XSS vulnerability.
=> RR-707 - Replaced multiline text filter with css

server/views/partials/workAndSkillsPage/goals/vc2GoalsOnly.njk
This PR fixes a problem on the Work & Skills tab in respect of displaying VC2 long term goals.
In our previous work on the W&S tab, we refactored the service classes and data types that populate the Work & Skills tab. Part of this change was to rename the view model property `learnerGoals` to `curiousGoals`. The thinking was that "learner goals" was a little too abstract, and whilst is a VC2/Curious term/data type, you need to know the internals of the Curious API to know this. Given that the scope of our work was to also add the PLP Goals to this page, we decided to rename `learnerGoals` to `curiousGoals`. With the addition of our new `plpGoals` property, it would then be clear which was which 👍 
In doing so we had to update the property name in the nunjucks view templates .... and it …
=> RR-720 - Fix display of VC2 long term goals on W&S tab

helm_deploy/values-preprod.yaml
This is for preprod
To configure moves to reception and cell move buttons on prisoner profile so they go to the new CSC service
=> MAP-794 changed CSC url for preprod

cypress.config.ts, feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, integration_tests/mockApis/prisonRegisterApi.ts, server/config.ts, server/data/interfaces/prisonRegisterApi/PrisonRegisterApiClient.ts, server/data/interfaces/prisonRegisterApi/prisonRegisterApiTypes.ts, server/data/localMockData/prisonRegisterMockData.ts, server/data/prisonRegisterApiClient.test.ts, server/data/prisonRegisterApiClient.ts
This PR adds a REST API client and associated config for calling the prison register API (will be used to lookup prison names from prison IDs in subsequent PRs)
=> RR-650 - Add prison register API client

README.md, integration_tests/e2e/addCaseNotePage.cy.ts, integration_tests/e2e/caseNotesPage.cy.ts, integration_tests/e2e/login.cy.ts, integration_tests/e2e/updateCaseNotePage.cy.ts, integration_tests/mockApis/caseNotesApi.ts, server/controllers/caseNotesController.test.ts, server/controllers/caseNotesController.ts, server/controllers/interfaces/OverviewPageData.ts, server/controllers/overviewController.ts, server/data/interfaces/caseNotesApi/caseNotesApiClient.ts, server/data/interfaces/prisonApi/PagedList.ts, server/middleware/checkPrisonerInCaseloadMiddleware.test.ts, server/middleware/checkPrisonerInCaseloadMiddleware.ts, server/routes/caseNotesRouter.ts, server/services/caseNotesService.test.ts, server/services/caseNotesService.ts
This PR enables us to use the client token to call the `offender-case-notes` API (with the one exception of the getTypesForUser call).
This allows us to drive (and correct) the rules for when users can create / edit / view case notes.
**The following issues are fixed in this PR:**
* When POM users were trying to legitimately create or view OMiC case notes for Restricted Patients, the Prison API part of the chain was rejecting the request because it does not consider the restricted patient's supported prison id when checking user caseload access.
* We were allowing users with POM and GLOBAL_SEARCH roles to access the case notes of restricted patients who are supported by a prison not in their caseload (https://mojdt.slack.com/archives/C01SNQDC10R/p1712332714758639)
=> CDPS-686: Using system token to make case notes API calls

integration_tests/e2e/overviewPage.cy.ts, server/controllers/utils/overviewController/buildOverviewActions.test.ts, server/controllers/utils/overviewController/buildOverviewActions.ts
This PR is for allowing users with the role PATHFINDER_USER to refer prisoners to pathfinder.
=> Allowed pathfinder user role to refer to pathfinder from the profile

server/app.ts, server/utils/azureAppInsights.ts
Marcus Aspin had seen a similar problem with their app responding with 502s that were not visible in app insights.  Turned out it was a memory leak issue due to paths not being normalised correctly for the Prometheus library: https://mojdt.slack.com/archives/C57UPMZLY/p1715763467600349?thread_ts=1715762197.517079&cid=C57UPMZLY
This PR is part 1 of parameterising our paths that are reported (in this case, to app insights).  This will be quite useful because when summarising requests/errors by name, we should get them grouped properly.
Pulled from update to typescript template: https://github.com/ministryofjustice/hmpps-template-typescript/pull/315/files#diff-226c1869e16c3e24e492b3483e64e2c58cca766e43b81632c01fb056ff8f666d
=> CDPS-721: Use parameterised paths in app insights

server/controllers/caseNotesController.ts, server/data/interfaces/caseNotesApi/CaseNoteSubType.ts, server/data/localMockData/caseNoteTypesMock.ts
MICN-164
`activeFlag` is now only used for Case Note Child type but not on Parent type.
and it is refactored into a boolean (`active`) in offender-case-notes service.
This PR updates case note api service to follow the updated API specs of offender-case-notes
=> MICN-164 Update case note subtype to use `active` prop instead of `activeFlag`

server/views/pages/appointments/prePostAppointments.njk
The court field and the hearing type field labels should be bolded to be consistent with the rest of the fields
=> Hearing type and court fonts to be bold during the create appointment journey

assets/js/prePostAppointment.js, cypress.config.ts, server/config.ts, server/controllers/appointmentController.ts, server/controllers/appointmentsController.test.ts, server/data/interfaces/locationsInsidePrisonApi/LocationsApiLocation.ts, server/data/interfaces/locationsInsidePrisonApi/LocationsInsidePrisonApiClient.ts, server/data/interfaces/nomisSyncPrisonerMappingApi/NomisSyncLocation.ts, server/data/interfaces/nomisSyncPrisonerMappingApi/NomisSyncPrisonerMappingApiClient.ts, server/data/interfaces/prisonApi/prisonApiClient.ts, server/data/interfaces/whereaboutsApi/Appointment.ts, server/data/localMockData/locationsMock.ts, server/data/locationsInsidePrisonApiClient.test.ts, server/data/locationsInsidePrisonApiClient.ts, server/data/nomisSyncPrisonerMappingClient.test.ts, server/data/nomisSyncPrisonerMappingClient.ts, server/data/prisonApiClient.test.ts, server/data/prisonApiClient.ts, server/services/appointmentService.test.ts, server/services/appointmentService.ts, server/services/index.ts, server/services/locationDetailsService.test.ts, server/services/locationDetailsService.ts, tests/mocks/locationsInsidePrisonApiClientMock.ts, tests/mocks/nomisSyncPrisonerMappingApiClientMock.ts, tests/mocks/prisonApiClientMock.ts, tests/mocks/prisonerLocationDetailsServiceMock.ts
The objective behind this code change is to replace calls that get location(s) from prison-api with calls to locations-inside-prison-api. 
The specific api endpoints changed are called by these functions in locationsInsidePrisonApiClient.ts. They have the same name as previously in prisonApiClient.
- getLocation
- getLocationsForAppointments
The key pages affected are 
- prisoner/{prisonNumber}/add-appointment
- prisoner/{prisonNumber}/appointment-confirmation
The nomis-sync-prisoner-mapping-api is used to get the corresponding location id between the prison-api and locations-inside-prison-api
Where used, dpsLocationId refers to the new uuid type id returned in the new locationsInsidePrisonApi object and nomisLocationId refers to the (current) integer type id  returned in the prisonApi …
=> MAP-1873 Swap to using locations-inside-prison-api for internal locations

assets/js/addAppointment.js, server/controllers/appointmentController.ts, server/controllers/appointmentsController.test.ts, server/views/pages/appointments/addAppointment.njk, server/views/pages/appointments/movementSlips.njk
This PR:
* Suppresses comments on movement slips for VLB (video court) and VLPM (video probation meetings), because they often contain contact details and personal info for attendees.
* It also show an optional label text on comment entry for these two appointment types to inform the user.
=> BAVL-623: Suppress movement slip comments for VLB and VLPM appointments only.

server/views/pages/appointments/appointmentConfirmation.njk, server/views/pages/appointments/prePostAppointmentConfirmation.njk, server/views/pages/appointments/prePostAppointments.njk
Small change for add appointment for BVLS court and probation to display 'None entered' for notes when nothing entered.
=> BAVL-900 small content changes for the BVLS court and probation appointment notes journeys.

package-lock.json, package.json
I needed the alert component introduced in 3.4.0.  I've checked the breaking changes in https://github.com/ministryofjustice/moj-frontend/releases/tag/v3.0.0 and there's nothing there that affects us.
=> CDPS-1376: Updating moj-frontend to 3.7.2

helm_deploy/values-dev.yaml
My team is working with a private prison operator's software provider by providing them API access to DPS services. They want to have access to dev DPS to complete the acceptance testing for a feature.
We have tried to provide them access to dev DPS for this, but they are getting 403 errors. We have a suspicion that this is an issue with the IP allowlisting.
To fix this, we have added a new group (kilco_uat) to the allowlists repo, and we would like to add kilco_uat as a group to dev here, as they need access to Prisoner Profiles, to see if the changes have worked.
=> Add Kilco UAT to dev allow list

assets/js/backToTop.js
The back to top link would overlay itself on other elements in an odd way when the header menu was open.
Now it hides itself if the header is intersecting the viewport.
=> BUG FIX CDPS-1364: Hide back to top when header visible

server/controllers/personal/personalController.ts, server/views/partials/personalPage/personalDetails.njk
It 404's when you get there because of caseload check failures. Since it's raised as a bug I figured hiding it in that case is the correct solution.
=> CDPS-1466: Hide 'Add UK Military service details' when prisoner not in caseload

assets/js/addAppointment.js, server/views/pages/appointments/addAppointment.njk, server/views/pages/appointments/movementSlips.njk
Of the 6 video appointment types, 2 are mastered in BVLS, and already collect separate staff and prisoner comments.
* VLB - video link court hearing
* VLPM - video link probation meeting
The 4 others are standard appointments and only have a single comments field, and are seen as a higher risk to potentially share external party names and contact details in their comments.
* VLLA - video link legal appointment
* VLPA - video link parole appointment
* VLOO - video link official other
* VLAP - video link with another prison.
This PR suppresses the comments on prisoner movement slips for these 4 appointment types.
=> BAVL-1074: Suppress comments from movement slips for 4 video appointment types

assets/scss/components/_personal-distinguishing-marks.scss, assets/scss/pages/_personal.scss
As part of this, I've also tweaked the distinguishing marks overlay images to fill the outline a bit better.
Before:
After:
=> CDPS-1447 Update personal page column widths

server/utils/dateHelpers.test.ts
Prevent issue in #1251 appearing again
=> Use fixed “now” when testing age calculation

integration_tests/mockApis/personIntegrationApi.ts, integration_tests/mockApis/prison.ts, integration_tests/mockApis/utils.ts
The image path `./../../assets/images/average-face.jpg` is supposed to be relative to the mock api typescript file, but wiremock cannot know that – so it’s always absent.
Cf. errors in all “Run wiremock” and “Run the node app” steps on CircleCI.
>  Error when working with FileSource:
> "Access to file ./../../assets/images/average-face.jpg is not permitted. An absolute path from the filesystem root might be specified"
> WARN HMPPS Prisoner Profile: Error calling Prison API, path: '/api/bookings/offenderNo/G6123VU/image/data?fullSizeImage=false', verb: 'GET' (responseStatus=500, data={}, message="Internal Server Error")
Using `base64Body ` in place of `bodyFileName` means that wiremock can simple reserve the content it was provided with.
=> Fix integration tests using wiremock to serve an image
